var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/onyx/agent-tools/register/route.js")
R.c("server/chunks/node_modules_next_594ba3a6._.js")
R.c("server/chunks/_97525657._.js")
R.c("server/chunks/node_modules_bcryptjs_index_42ebb250.js")
R.c("server/chunks/node_modules_next_dist_e341186c._.js")
R.c("server/chunks/[root-of-the-server]__ae5d6a65._.js")
R.c("server/chunks/_259ee7a2._.js")
R.c("server/chunks/[root-of-the-server]__e3324220._.js")
R.c("server/chunks/_next-internal_server_app_api_onyx_agent-tools_register_route_actions_7a195a5e.js")
R.m(427228)
module.exports=R.m(427228).exports
