var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/painel-alpha/clientes/[id]/timeline/route.js")
R.c("server/chunks/[root-of-the-server]__84a48906._.js")
R.c("server/chunks/_3d24d410._.js")
R.c("server/chunks/node_modules_bcryptjs_index_42ebb250.js")
R.c("server/chunks/node_modules_next_594ba3a6._.js")
R.c("server/chunks/_97525657._.js")
R.c("server/chunks/_259ee7a2._.js")
R.c("server/chunks/[root-of-the-server]__ae5d6a65._.js")
R.c("server/chunks/node_modules_next_dist_e341186c._.js")
R.c("server/chunks/ce889_server_app_api_painel-alpha_clientes_[id]_timeline_route_actions_9c8600bf.js")
R.m(979838)
module.exports=R.m(979838).exports
