var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/bpm/jobs/alertas-tarefas/route.js")
R.c("server/chunks/src_lib_bpm_5766b477._.js")
R.c("server/chunks/node_modules_next_594ba3a6._.js")
R.c("server/chunks/src_lib_bpm_65043f8e._.js")
R.c("server/chunks/_97525657._.js")
R.c("server/chunks/[root-of-the-server]__a81f0ba9._.js")
R.c("server/chunks/[root-of-the-server]__f7a9ec92._.js")
R.c("server/chunks/[root-of-the-server]__ae5d6a65._.js")
R.c("server/chunks/_021b959e._.js")
R.c("server/chunks/node_modules_next_dist_e341186c._.js")
R.c("server/chunks/node_modules_zod_v4_76b20a3c._.js")
R.c("server/chunks/_next-internal_server_app_api_bpm_jobs_alertas-tarefas_route_actions_7a739ec4.js")
R.m(655445)
module.exports=R.m(655445).exports
