var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/alpha-explorer/smb/health/route.js")
R.c("server/chunks/node_modules_next_594ba3a6._.js")
R.c("server/chunks/node_modules_bcryptjs_index_42ebb250.js")
R.c("server/chunks/[root-of-the-server]__ae5d6a65._.js")
R.c("server/chunks/_97525657._.js")
R.c("server/chunks/node_modules_next_dist_e341186c._.js")
R.c("server/chunks/_259ee7a2._.js")
R.c("server/chunks/node_modules_zod_v4_613370e3._.js")
R.c("server/chunks/[root-of-the-server]__6e5c3cf3._.js")
R.c("server/chunks/_next-internal_server_app_api_alpha-explorer_smb_health_route_actions_c8d507c2.js")
R.m(191375)
module.exports=R.m(191375).exports
