var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/ChatBot/route.js")
R.c("server/chunks/[root-of-the-server]__c348f420._.js")
R.c("server/chunks/_97525657._.js")
R.c("server/chunks/node_modules_next_594ba3a6._.js")
R.c("server/chunks/[root-of-the-server]__ae5d6a65._.js")
R.c("server/chunks/_259ee7a2._.js")
R.c("server/chunks/node_modules_next_dist_e341186c._.js")
R.c("server/chunks/node_modules_bcryptjs_index_42ebb250.js")
R.c("server/chunks/_next-internal_server_app_api_ChatBot_route_actions_68c2cd70.js")
R.m(106231)
module.exports=R.m(106231).exports
