var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/chat/upload/route.js")
R.c("server/chunks/[root-of-the-server]__c64c33eb._.js")
R.c("server/chunks/node_modules_next_dist_e341186c._.js")
R.c("server/chunks/node_modules_next_594ba3a6._.js")
R.c("server/chunks/node_modules_c0de9c77._.js")
R.c("server/chunks/[root-of-the-server]__ae5d6a65._.js")
R.c("server/chunks/node_modules_b3398e44._.js")
R.c("server/chunks/_next-internal_server_app_api_chat_upload_route_actions_1946ad6d.js")
R.m(752839)
module.exports=R.m(752839).exports
